version: '3'
services:
    db:
        container_name: "techical-training-postgres"
        restart: unless-stopped
        image: postgres:12
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - POSTGRES_DB=postgres
        volumes:
            - ./PATH_17/postgres-data:/var/lib/postgresql/data
    odoo:
        container_name: "techical-training-odoo"
        restart: unless-stopped
        image: odoo:17
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - ./:/mnt/extra-addons
            - ./etc:/etc/odoo
